"""Add Checked Column

Revision ID: 967abe324dff
Revises: bac50eb21fb2
Create Date: 2023-09-24 14:01:26.500338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967abe324dff'
down_revision = 'bac50eb21fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_home', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked', sa.Boolean(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('checkout_pickup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked', sa.Boolean(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_pickup', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('checked')

    with op.batch_alter_table('checkout_home', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('checked')

    # ### end Alembic commands ###
